









WINDOW_SEC: float = 10.0
N_TOKENS_PER_SEC: int = 4
N_TOKENS: int = int(WINDOW_SEC * N_TOKENS_PER_SEC)


FMRI_TR: float = 2.0
FMRI_N_TIMEPOINTS: int = int(WINDOW_SEC / FMRI_TR)


FMRI_N_MODES: int = 2000
FMRI_N_GROUPS: int = N_TOKENS // FMRI_N_TIMEPOINTS
assert FMRI_N_MODES % FMRI_N_GROUPS == 0, (
    f"FMRI_N_MODES ({FMRI_N_MODES}) must be divisible by FMRI_N_GROUPS ({FMRI_N_GROUPS})"
)



NEUROSTORM_SPATIAL_FLAT: int = 288 * 2 * 2 * 2
NEUROSTORM_N_SPATIAL_GROUPS: int = N_TOKENS // FMRI_N_TIMEPOINTS
assert NEUROSTORM_SPATIAL_FLAT % NEUROSTORM_N_SPATIAL_GROUPS == 0, (
    f"NEUROSTORM_SPATIAL_FLAT ({NEUROSTORM_SPATIAL_FLAT}) must be divisible by "
    f"NEUROSTORM_N_SPATIAL_GROUPS ({NEUROSTORM_N_SPATIAL_GROUPS})"
)


EEG_SAMPLE_RATE: int = 256
EEG_MEG_N_SAMPLES: int = int(WINDOW_SEC * EEG_SAMPLE_RATE)



EEGMEG_PRIOR_PATCH_SIZE: int = EEG_MEG_N_SAMPLES // N_TOKENS
EEGMEG_PRIOR_PATCH_STRIDE: int = EEGMEG_PRIOR_PATCH_SIZE
assert (EEG_MEG_N_SAMPLES - EEGMEG_PRIOR_PATCH_SIZE) % EEGMEG_PRIOR_PATCH_STRIDE == 0, (
    "Patch parameters do not evenly tile the time series."
)
_EEGMEG_PRIOR_N_TOKENS_CHECK: int = (
    (EEG_MEG_N_SAMPLES - EEGMEG_PRIOR_PATCH_SIZE) // EEGMEG_PRIOR_PATCH_STRIDE + 1
)
assert _EEGMEG_PRIOR_N_TOKENS_CHECK == N_TOKENS, (
    f"Patch formula gives {_EEGMEG_PRIOR_N_TOKENS_CHECK} tokens, expected {N_TOKENS}"
)



_BRAINOMNI_BACKBONE_N_TOKENS: int = 56


BRAINOMNI_N_TOKENS: int  = N_TOKENS
NEUROSTORM_N_TOKENS: int = N_TOKENS
FMRI_PRIOR_N_TOKENS: int = N_TOKENS
EEGMEG_PRIOR_N_TOKENS: int = N_TOKENS


D_MODEL: int = 1024
D_LLM: int = 2048






FUSION_MODE: str = "full"
